style: github
template: CHANGELOG.md.tpl.md
info:
  title: CHANGELOG.md
  repository_url: https://github.com/umotif-public/terraform-aws-waf-webaclv2
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject